"use client";
import { useEffect, useState } from "react";
import { getCottage } from "@/lib/cottages";
import type { Cottage } from "@/lib/types";
import AvailabilityCalendar from "./AvailabilityCalendar";
import { MapPin, Users, Mail, Phone } from "lucide-react";
export default function CottageDetailClient({id}:{id:string}){
 const [c,setC]=useState<Cottage|null>(null); const [active,setActive]=useState(0);
 useEffect(()=>{getCottage(id).then(setC)},[id]); if(!c)return <div className="p-10">Ladataan...</div>;
 const imgs=c.images?.length?c.images:[c.image||"/hero.jpg"];
 const amenities=Object.entries(c.amenities||{}).filter(([,v])=>v).map(([k])=>({sauna:"Sauna",beach:"Oma ranta",hotTub:"Palju",boat:"Vene",pets:"Lemmikit sallittu",electricity:"Sähköt",drinkingWater:"Juomavesi",indoorToilet:"Sisä-WC"}[k]||k));
 return <main className="mx-auto max-w-[1400px] px-5 py-8"><div className="grid gap-3 md:grid-cols-[2fr_1fr]"><img src={imgs[active]} className="h-[520px] w-full rounded-2xl object-cover"/><div className="grid grid-cols-2 gap-3">{imgs.slice(0,4).map((img,i)=><button key={i} onClick={()=>setActive(i)}><img src={img} className="h-[254px] w-full rounded-2xl object-cover"/></button>)}</div></div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_420px]"><article><p className="font-black uppercase tracking-widest text-forest">{c.city}</p><div className="flex flex-wrap items-start justify-between gap-4"><h1 className="mt-2 text-5xl font-black">{c.name}</h1><p className="text-3xl font-black">{c.price} € <span className="text-base font-normal">/ yö</span></p></div><div className="mt-5 flex flex-wrap gap-5 text-slate-600"><span className="flex gap-2"><MapPin/>{c.city}</span><span className="flex gap-2"><Users/>{c.guests} henkilöä</span></div><p className="mt-8 whitespace-pre-line text-lg leading-8">{c.description}</p><h2 className="mt-10 text-2xl font-black">Varustelu</h2><div className="mt-4 grid grid-cols-2 gap-3">{amenities.map(a=><div key={a} className="rounded-xl bg-cream p-4 font-semibold">✓ {a}</div>)}</div><h2 className="mt-10 text-2xl font-black">Sijainti</h2><div className="mt-4 h-72 overflow-hidden rounded-2xl bg-slate-100">{c.latitude&&c.longitude?<iframe className="h-full w-full" src={`https://www.openstreetmap.org/export/embed.html?bbox=${c.longitude-.08}%2C${c.latitude-.05}%2C${c.longitude+.08}%2C${c.latitude+.05}&layer=mapnik&marker=${c.latitude}%2C${c.longitude}`}/>:<div className="grid h-full place-items-center">Sijainti tarkentuu myöhemmin</div>}</div></article><aside className="space-y-5"><AvailabilityCalendar ranges={c.blockedRanges}/><div className="rounded-2xl border p-6 shadow-lg"><h2 className="text-2xl font-black">Lähetä varauspyyntö</h2><input type="date" className="mt-4 w-full rounded-xl border p-3"/><input type="date" className="mt-3 w-full rounded-xl border p-3"/><input placeholder="Nimi" className="mt-3 w-full rounded-xl border p-3"/><input placeholder="Sähköposti" className="mt-3 w-full rounded-xl border p-3"/><textarea placeholder="Viesti omistajalle" className="mt-3 min-h-28 w-full rounded-xl border p-3"/><a href={`mailto:${c.email}?subject=Varauspyyntö: ${encodeURIComponent(c.name)}`} className="mt-4 block rounded-xl bg-forest p-4 text-center font-black text-white">Lähetä varauspyyntö</a><div className="mt-5 space-y-2 text-sm text-slate-600">{c.email&&<p className="flex gap-2"><Mail size={17}/>{c.email}</p>}{c.phone&&<p className="flex gap-2"><Phone size={17}/>{c.phone}</p>}</div></div></aside></div></main>
}
